In [33]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,recall_score
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split

## 2. Data collection

In [34]:
diabets_data = pd.read_csv("diabetes.csv")
diabets_data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

## 3. Data understanding

In [35]:
diabets_data.shape

(768, 9)

In [36]:
diabets_data.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [37]:
diabets_data.duplicated().sum()

np.int64(0)

In [38]:
diabets_data.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [39]:
diabets_data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

## 4. Data preparation

In [40]:
x = diabets_data.drop("Outcome",axis=1)
y = diabets_data["Outcome"]

## 5. Model Building

In [41]:
model = Sequential()

In [51]:
model.add(Dense(units=100,input_dim=8,kernel_initializer='uniform',activation="relu"))
model.add(Dense(units=68,kernel_initializer='uniform',activation="relu"))
model.add(Dense(1,kernel_initializer='uniform',activation="sigmoid"))

C:\Users\vishw\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [58]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [59]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,stratify=y)

In [60]:
x_train.shape,x_test.shape

((614, 8), (154, 8))

In [61]:
std = StandardScaler()
x_train = std.fit_transform(x_train)
x_test = std.transform(x_test)

In [69]:
model.fit(x=x_train,y=y_train,batch_size=16,epochs=50,validation_split=0.2)

Epoch 1/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.9654 - loss: 0.1458 - val_accuracy: 0.8211 - val_loss: 0.5412
Epoch 2/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.9776 - loss: 0.1199 - val_accuracy: 0.8455 - val_loss: 0.4717
Epoch 3/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.9776 - loss: 0.1160 - val_accuracy: 0.8374 - val_loss: 0.4977
Epoch 4/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.9776 - loss: 0.1147 - val_accuracy: 0.8374 - val_loss: 0.4943
Epoch 5/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.9776 - loss: 0.1147 - val_accuracy: 0.8211 - val_loss: 0.5175
Epoch 6/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.9776 - loss: 0.1136 - val_accuracy: 0.8211 - val_loss: 0.5443
Epoch 7/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.9776 - loss: 0.1131 - val_accuracy: 0.8130 - val_loss: 0.5301
Epoch 8/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9776 - loss: 0.1133 - val_accuracy: 0.8130 - val_loss: 0.5414
Epoch 9/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.9776 - loss: 0.1132 - val_accuracy: 0.8211 - val_loss: 0.5632
Epoch 10/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.9776 - loss: 0.1127 - val_accuracy: 0.8211 - val_loss: 0.5562
Epoch 11/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 2s 59ms/step - accuracy: 0.9776 - loss: 0.1128 - val_accuracy: 0.8130 - val_loss: 0.5492
Epoch 12/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.9776 - loss: 0.1123 - val_accuracy: 0.8130 - val_loss: 0.5558
Epoch 13/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 0.9776 - loss: 0.1130 - val_accuracy: 0.8211 - val_loss: 0.5702
Epoch 14/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.9776 - loss: 0.1123 - val_accuracy: 0.8130 - val_loss: 0.5455
Epoch 15/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.9776 - loss: 0.1120 - val_accuracy: 0.8130 - val_loss: 0.5651
Epoch 16/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9776 - loss: 0.1118 - val_accuracy: 0.8211 - val_loss: 0.5826
Epoch 17/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.9776 - loss: 0.1116 - val_accuracy: 0.8130 - val_loss: 0.5705
Epoch 18/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.9776 - loss: 0.1118 - val_accuracy: 0.8211 - val_loss: 0.5850
Epoch 19/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.9776 - loss: 0.1131 - val_accuracy: 0.8130 - val_loss: 0.5725
Epoch 20/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.9776 - loss: 0.1114 - val_accuracy: 0.8211 - val_loss: 0.5828
Epoch 21/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.9776 - loss: 0.1114 - val_accuracy: 0.8130 - val_loss: 0.5656
Epoch 22/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.9776 - loss: 0.1117 - val_accuracy: 0.8211 - val_loss: 0.5813
Epoch 23/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.9776 - loss: 0.1112 - val_accuracy: 0.8211 - val_loss: 0.5871
Epoch 24/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.9776 - loss: 0.1115 - val_accuracy: 0.8211 - val_loss: 0.5949
Epoch 25/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.9776 - loss: 0.1116 - val_accuracy: 0.8130 - val_loss: 0.5850
Epoch 26/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.9776 - loss: 0.1116 - val_accuracy: 0.8130 - val_loss: 0.5763
Epoch 27/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.9776 - loss: 0.1114 - val_accuracy: 0.8211 - val_loss: 0.6060
Epoch 28/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.9776 - loss: 0.1106 - val_accuracy: 0.8130 - val_loss: 0.5858
Epoch 29/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.9776 - loss: 0.1114 - val_accuracy: 0.8130 - val_loss: 0.5671
Epoch 30/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.9776 - loss: 0.1108 - val_accuracy: 0.8211 - val_loss: 0.5971
Epoch 31/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.9776 - loss: 0.1106 - val_accuracy: 0.8130 - val_loss: 0.5750
Epoch 32/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.9776 - loss: 0.1102 - val_accuracy: 0.8130 - val_loss: 0.5981
Epoch 33/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.9776 - loss: 0.1112 - val_accuracy: 0.8130 - val_loss: 0.5969
Epoch 34/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.9776 - loss: 0.1105 - val_accuracy: 0.8211 - val_loss: 0.5922
Epoch 35/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.9776 - loss: 0.1103 - val_accuracy: 0.8130 - val_loss: 0.5882
Epoch 36/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.9776 - loss: 0.1101 - val_accuracy: 0.8130 - val_loss: 0.6085
Epoch 37/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.9776 - loss: 0.1104 - val_accuracy: 0.8211 - val_loss: 0.5990
Epoch 38/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.9776 - loss: 0.1106 - val_accuracy: 0.8049 - val_loss: 0.6271
Epoch 39/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.9776 - loss: 0.1102 - val_accuracy: 0.8130 - val_loss: 0.6068
Epoch 40/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.9776 - loss: 0.1104 - val_accuracy: 0.8130 - val_loss: 0.5986
Epoch 41/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.9776 - loss: 0.1100 - val_accuracy: 0.8211 - val_loss: 0.6229
Epoch 42/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.9776 - loss: 0.1109 - val_accuracy: 0.8211 - val_loss: 0.6057
Epoch 43/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9776 - loss: 0.1101 - val_accuracy: 0.8211 - val_loss: 0.5957
Epoch 44/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.9776 - loss: 0.1104 - val_accuracy: 0.8211 - val_loss: 0.6044
Epoch 45/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.9776 - loss: 0.1105 - val_accuracy: 0.8130 - val_loss: 0.6057
Epoch 46/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.9776 - loss: 0.1100 - val_accuracy: 0.8130 - val_loss: 0.6070
Epoch 47/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.9776 - loss: 0.1104 - val_accuracy: 0.8130 - val_loss: 0.5791
Epoch 48/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.9776 - loss: 0.1102 - val_accuracy: 0.8211 - val_loss: 0.6312
Epoch 49/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.9776 - loss: 0.1103 - val_accuracy: 0.8130 - val_loss: 0.6139
Epoch 50/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.9776 - loss: 0.1094 - val_accuracy: 0.8130 - val_loss: 0.6321

In [71]:
y_pred = model.predict(x_test)
y_pred = (y_pred>0.6).astype(int)
y_pred

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step

array([[1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0]])

In [72]:
model.save("diabetes.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

## 10 New Data

In [79]:
from keras.models import load_model
diabetes_ped = load_model("diabetes.h5")

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [73]:
import numpy as np

In [95]:
new_data = np.array([[10,50,69,0.2,0.6,0.8,8.5,9.2]])
new_data = std.transform(new_data)
ac_ped = diabetes_ped.predict(new_data)
print("prbo:",ac_ped)
class_pred = (ac_ped >0.6).astype(int)
print(class_pred[0][0])

C:\Users\vishw\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 291ms/step
prbo: [[0.01215878]]
0